name: pub_client
description: >
  A library for interacting with the REST API for Pub (pub.dartlang.org/api).
environment:
  sdk: '^3.4.0'
version: 3.0.3
author: Jim Simon <jim.j.simon@gmail.com>
homepage: https://github.com/jimsimon/pub_client
dependencies:
  http: ^1.2.1
  json_annotation: ^4.9.0
dev_dependencies:
  build_runner: ^2.4.11
  json_serializable: ^6.8.0
  test: any
  path: ^1.9.0
