name: pub_client
description: >
  A library for interacting with the REST API for Pub (pub.dev.org/api).
environment:
  sdk: '>=2.1.0 <3.0.0'
version: 3.1.4
author: Jim Simon <jim.j.simon@gmail.com>
homepage: https://github.com/jimsimon/pub_client

dependencies:
  http: ^0.12.0+2
  json_annotation: ">=1.0.0 <3.0.0"
  gcloud: '^0.6.0'
  pub_semver: ^1.4.2
  intl: '>=0.13.0 <0.16.0'
  html: ^0.13.3

dev_dependencies:
  build_runner: ">=0.10.1 <2.0.0"
  json_serializable: ">=1.0.1 <3.0.0"
  test: any
  path: ^1.6.2
  json_model: