name: pub_client
description: >
  A library for interacting with the REST API for Pub (pub.dartlang.org/api).
version: 1.0.5
author: Jim Simon <jim.j.simon@gmail.com>
homepage: https://github.com/jimsimon/pub_client
dependencies:
  http: ">=0.11.2 <0.12.0"
  dartson: ">=0.2.2 <0.3.0"
dev_dependencies:
  unittest: ">=0.11.5+4 <0.12.0"