name: pub_client
description: >
  A library for interacting with the REST API for Pub (pub.dartlang.org).
version: 1.0.0
author: Jim Simon <jim.j.simon@gmail.com>
dependencies:
  http: ">=0.11.2 <0.12.0"
  jsonx: ">=2.0.0 <3.0.0"
dev_dependencies:
  unittest: any