name: pub_client
description:
  A Dart wrapper for the pub.dev website.
environment:
  sdk: '>=2.6.0 <3.0.0'
version: 3.7.1
authors:
  - Jim Simon <jim.j.simon@gmail.com>
  - Jonathan White <jwhite@thinkdigital.software>
homepage: https://github.com/jimsimon/pub_client

dependencies:
  http: ^0.12.2
  json_annotation: ^3.0.1

  intl: ^0.16.1
  html: ^0.14.0+3
  simple_smart_scraper: ^1.0.21

dev_dependencies:
  json_serializable: ^3.3.0
  test: ^1.15.3
  path: ^1.7.0
